/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busquedas;

import javax.swing.JFileChooser;
import java.io.FileOutputStream; 
import java.io.IOException; 
import java.io.ObjectOutputStream;  
import java.util.NoSuchElementException; 
import java.util.Scanner; 
import javax.swing.JOptionPane;
import java.io.*;
import java.util.Random;

/**
 *
 * @author andy
 */
public class CrearEmpleados extends javax.swing.JFrame {
JFileChooser seleccionado=new JFileChooser();
String direccion="";
    /**
     * Creates new form CrearEmpleados
     */
    public CrearEmpleados() {
        initComponents();
    }
    
    
    static Random r= new Random();

//    public static void main (String [] args )throws IOException{
//        iniciar();   
//    }

    public static void iniciar(String link) throws IOException{

        File salida = new File(link);
        FileOutputStream Archivo = new FileOutputStream(salida);
        ObjectOutputStream esobj = new ObjectOutputStream(Archivo);
        String hom[]={"Antonio","Abraham","Abel","Adan","Alejandro","Alfonso","Alvaro","Alfredo","Angel","Arturo","Jorge","Aurelio","Federico",
                "Felipe","Fernando","Fidel","Francisco","Andres","Gabriel","Gonzalo","Luis","Hugo","Ismael","Jacob","Jaime"};
        String muj[]={"Ana","Laura","Ines","Isabel", "Monica", "Natalia","Lucero","Lidia", "Matilde", "Jaquelin", "Mariana", "Priscila","Julia",
                "Huri", "Silvana","Sofia","Elisa","Nilda", "Victoria", "Rosalia","Magaly", "Leslie", "Gabriela","Araceli","Allison"};
        String ap[]={"Lopez","Rios","Bautista","Velasco","Canseco","Bazan","Baños","Robles","Medina","Antonio","Espinoza","Navarro",
                "Arango","Rodriguez","Barroso","Sanchez","Juarez","Hernandez","Quintana","Valdes","Silva","Baños","Diaz","Camacho","Calvo"};

        System.out.printf( "%-8s%-17s%-32s%-6s%-5s\n","Numero","Clave","Nombre","Sexo","Edad" );
        for(int i=1; i<201; i++){
            genX();
            geSe();
            if(geSe()==1){
                String nombre=hom[genX()]+" "+ ap[genX()]+" "+ ap[genX()];
                Persona  p=new Persona(ran(),nombre,"H",generarE());
                esobj.writeObject(p);
                // System.out.println(i+" "+ p);
                System.out.printf( "%-8s%-17s%-32s%-6s%-5s\n",i,p.getClave(),p.getNombre(),p.getSexo(),p.getEdad());
            }else{
                String nombre=muj[genX()]+" "+ ap[genX()]+" "+ ap[genX()];
                Persona  p=new Persona(ran(),nombre,"F",generarE());
                esobj.writeObject(p);
                //  System.out.println(i+" "+ p);
                System.out.printf( "%-8s%-17s%-32s%-6s%-5s\n",i,p.getClave(),p.getNombre(),p.getSexo(),p.getEdad());
            }
        }
        esobj.close();
    }

    public static int generarE(){
        int e=18+r.nextInt(42);

        return e;
    }

    public static int genX(){
        int e=0+r.nextInt(24);

        return e;
    }

    public static int generarNC(){
        int n=0+r.nextInt(40000);

        return n;
    }

    public static int geSe(){
        int sex=(int)(Math.random()*2+1);   
        return sex;
    }
     public static int ran(){
        int e=0;
        while((e+"").length()<8)
            e=0+r.nextInt(40000000);

        return e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Generador de Datos");

        jPanel1.setBackground(new java.awt.Color(0, 255, 0));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Crear Empleados");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("Generador de Datos - Elija una Opcion:");

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Realizar Busquedas");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Salir");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(59, 59, 59))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(33, 33, 33)
                .addComponent(jButton3)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
        if(seleccionado.showSaveDialog(null)==seleccionado.APPROVE_OPTION){
            direccion=seleccionado.getSelectedFile().getAbsolutePath();
            iniciar(direccion);
        }
        }catch(Exception e){
            e.printStackTrace();
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         System.exit(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }

        });
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
